wallpaper {
    monitor =                                   # Vacio para que sea independiente del monito
    path = ~/Pictures/Wallpapers/Wallpo.png
    fit_mode = cover
}
splash = false                                  # Elimina el mensaje de la parte inferior
