wallpaper {
    monitor =                                   # Vacio para que sea independiente del monito
    path = ~/Imágenes/Wallpapers/Wallpo1.png    # Solo hasta que arranca Quickshell la primera vez: luego manda la config que genera Wallpaper.qml, con la carpeta de imágenes de verdad
    fit_mode = cover
}
splash = false                                  # Elimina el mensaje de la parte inferior
